### ISSUE TITLE
xAntiAFK placeholders are not parsed in the TAB

### ISSUE THREAD

**Issue by bloodycoffin** [ArchitectSMP/k8s-gitops#106]
![image](https://user-images.githubusercontent.com/78444107/110172438-6c2cb800-7dfd-11eb-8125-ec368c7a8b25.png)

**Comment by ChipWolf** [comment]
Spoke to the TAB developer, it's not anything to do with TAB.
We did find however if we remove DiscordSRV from the servers, it resolves this.
