### ISSUE TITLE
Wandering traders are ... bouncing?

### ISSUE THREAD

**Issue by FlooferDoofer** [ArchitectSMP/k8s-gitops#136]
Wandering Traders keep jumping while nodding its head, making it unable to trade with them.
Pushing them around, putting them in a hole, making them fall a short distance all don't make a difference.

Putting them in a boat or in a hole with one level of water seems to stop the movement enough to be able to trade with them.

The nodding looks like he is lost interest and then notices the player again.

Issue has been observed on 4 different occasions, with different Traders and locations, by different players.

**Comment by bloodycoffin** [comment]
@ChipWolf I don't remember us amending anything that would impact Wandering Traders. I also can't find anything on Wandering Traders continuously jumping. Any ideas?
It has been observed for a few days, not anything to do with this?
https://github.com/ArchitectSMP/k8s-gitops/commit/2449b892fc84c2c586650046d832443a571342fa

**Comment by ChipWolf** [comment]
Yeah, nothing to do with the chart/container, it's an application issue so defer to Paper?

**Comment by bloodycoffin** [comment]
Did the paper version change with the maintenance or did it somehow update without my knowledge?

**Comment by bloodycoffin** [comment]
@ChipWolf  " I am running the latest version of Paper available from https://papermc.io/downloads. *"

This server is running Paper version git-Paper-558 (MC:1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 6 version(s) behind.

Since we are currently not up-to-date I am technically not allowed to log an issue on their Github.
Can we update or is something keeping us behind?

**Comment by ChipWolf** [comment]
The container grabs the latest version of paper when started https://github.com/itzg/docker-minecraft-server/blob/master/start-deployPaper#L20

**Comment by bloodycoffin** [comment]
According to today's check the survival is still 1 version behind.
Will a restart of the Survival + Creative + Bungee Proxy server update Paper?

**Comment by ChipWolf** [comment]
Just running `/stop` will make it come back up with the latest version
The Paper version is specified as `latest`, we just specify the Minecraft version as `1.16.5` to prevent any future updates causing problems.

**Comment by bloodycoffin** [comment]
Right now the Wandering Traders are no longer bouncing around, if a new case is presented we can re-open
