### ISSUE TITLE
Dev servers not reachable in Minecraft Launcher

### ISSUE THREAD

**Issue by bloodycoffin** [ArchitectSMP/k8s-gitops#137]
Possibly servers not restored after maintenance - had to put back the plugins
Discord SRV responds to Discord so it is working
Also the kubectl get pods -n dev command does return running servers, I just can't connect through the Minecraft Launcher

**Comment by bloodycoffin** [comment]
Prod data copied to Dev since Dev wasn't restored
Servers still not reachable in Minecraft Launcher

**Comment by bloodycoffin** [comment]
@ChipWolf can't perform any tests atm or check out new plugins because Dev is unreachable
If you have any time can you check this out? I am kind of stuck in my issues now :-)

**Comment by ChipWolf** [comment]
Resolved, files in the dev pvs needed to be chown'd to 1000:2000

**Comment by ChipWolf** [comment]
Please confirm @bloodycoffin

**Comment by bloodycoffin** [comment]
can't access 
![image](https://user-images.githubusercontent.com/78444107/112391438-342bdd00-8cf8-11eb-8c17-dba175ca4316.png)
@ChipWolf

**Comment by ChipWolf** [comment]
```shell
chip@artemis ~ # kubectl get service minecraft-proxy-minecraft-proxy -n dev
NAME                              TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)           AGE
minecraft-proxy-minecraft-proxy   LoadBalancer   10.43.31.122   <pending>     25565:32451/TCP   12d
```

Looks like the proxy isn't being allocated the IP it's asking for, looking into it.

**Comment by ChipWolf** [comment]
The change was missed in https://github.com/ArchitectSMP/k8s-gitops/commit/94836ce42b2102e3f01e6be20bda95900f7eba97
