### ISSUE TITLE
Players can't connect to server

### ISSUE THREAD

**Issue by bloodycoffin** [ArchitectSMP/k8s-gitops#189]
There seem to be connection issues at European night time for players. At first it was the 3 new Canadians 2 of them have not reported the problems repeating itself after the first time, the third one just had it last night but could connect fine before that and play for a while. When he changed during his problems to Austrian VPN the problems were a lot less noticable.
However tonight Flooferdoofer and _RoAd_ also got kicked out of the server. At first a launcher restart fixed the problem only for them (not for stormfly - Canadian), after they could not connect at all.

**Comment by bloodycoffin** [comment]
Stormfly tracert:

1    <1 ms    <1 ms    <1 ms  192.168.2.1
2   618 ms   688 ms   266 ms  10.11.7.113
3     *        *        *     Request timed out.
4     4 ms     4 ms     3 ms  toroon12xfw_0/2/0/5_11.net.bell.ca [142.124.127.74]
5     8 ms     7 ms     6 ms  tcore4-toronto12-bundle-ether41.net.bell.ca [142.124.127.196]
6     2 ms     2 ms     2 ms  dis45-toronto12_7-0-0.net.bell.ca [64.230.104.181]
7    19 ms    20 ms    19 ms  bx10-newyork83_ae1.net.bell.ca [64.230.79.211]
8    19 ms    21 ms    25 ms  ae9-0.nyk10.core-backbone.com [80.255.14.73]
9    90 ms    90 ms    90 ms  ae2-2021.fra20.core-backbone.com [80.255.14.6]
10    90 ms    90 ms    94 ms  core-backbone.hetzner.com [80.255.15.122]
11    98 ms    98 ms    98 ms  core24.fsn1.hetzner.com [213.239.224.253]
12    95 ms    95 ms    96 ms  ex9k3.dc8.fsn1.hetzner.com [213.239.229.142]
13    98 ms    98 ms    98 ms  static.147.203.201.138.clients.your-server.de [138.201.203.147]
14     *        *        *     Request timed out. (and it continues with timeouts)

**Comment by bloodycoffin** [comment]
Road tracert:

1    <1 ms    <1 ms    <1 ms  192.168.2.254
  2     3 ms     1 ms     1 ms  195-190-228-83.fixed.kpn.net [195.190.228.83]
  3     *        *        3 ms  139.156.98.100
  4     *        *        *     Request timed out.
  5     *        *     1136 ms  ae0.fix5-r1.de.syseleven.net [185.56.105.14]
  6     *        *        *     Request timed out.
  7     *        *     2123 ms  core24.fsn1.hetzner.com [213.239.229.78]
  8     *     1070 ms     *     ex9k3.dc8.fsn1.hetzner.com [213.239.229.142]
  9     *        *        *     Request timed out.
 10     *        *        *     Request timed out.
 11     *        *        *     Request timed out.
 12     *        *        *     Request timed out.

**Comment by ChipWolf** [comment]
> 
> 
> Stormfly tracert:
> 
> 1 <1 ms <1 ms <1 ms 192.168.2.1
> 2 618 ms 688 ms 266 ms 10.11.7.113
> 3 * * * Request timed out.
> 4 4 ms 4 ms 3 ms toroon12xfw_0/2/0/5_11.net.bell.ca [142.124.127.74]
> 5 8 ms 7 ms 6 ms tcore4-toronto12-bundle-ether41.net.bell.ca [142.124.127.196]
> 6 2 ms 2 ms 2 ms dis45-toronto12_7-0-0.net.bell.ca [64.230.104.181]
> 7 19 ms 20 ms 19 ms bx10-newyork83_ae1.net.bell.ca [64.230.79.211]
> 8 19 ms 21 ms 25 ms ae9-0.nyk10.core-backbone.com [80.255.14.73]
> 9 90 ms 90 ms 90 ms ae2-2021.fra20.core-backbone.com [80.255.14.6]
> 10 90 ms 90 ms 94 ms core-backbone.hetzner.com [80.255.15.122]
> 11 98 ms 98 ms 98 ms core24.fsn1.hetzner.com [213.239.224.253]
> 12 95 ms 95 ms 96 ms ex9k3.dc8.fsn1.hetzner.com [213.239.229.142]
> 13 98 ms 98 ms 98 ms static.147.203.201.138.clients.your-server.de [138.201.203.147]
> 14 * * * Request timed out. (and it continues with timeouts)

This indicates an issue with the user's router or their ISP, see the second line (the first hop outside of their NAT to their ISP's WAN)

**Comment by ChipWolf** [comment]
> 
> 
> Road tracert:
> 
> 1 <1 ms <1 ms <1 ms 192.168.2.254
> 2 3 ms 1 ms 1 ms 195-190-228-83.fixed.kpn.net [195.190.228.83]
> 3 * * 3 ms 139.156.98.100
> 4 * * * Request timed out.
> 5 * * 1136 ms ae0.fix5-r1.de.syseleven.net [185.56.105.14]
> 6 * * * Request timed out.
> 7 * * 2123 ms core24.fsn1.hetzner.com [213.239.229.78]
> 8 * 1070 ms * ex9k3.dc8.fsn1.hetzner.com [213.239.229.142]
> 9 * * * Request timed out.
> 10 * * * Request timed out.
> 11 * * * Request timed out.
> 12 * * * Request timed out.

The issue with this user's connection becomes evident at hop 5, you see the packet has reasonable timings through their ISP, but then we see it transit through `syseleven.net` where the latency dramatically increases.

SysEleven provides carrier transit services, but they're not a T1 network, so I think this user's ISP has poor routing through slow transits; presumably to cut the costs of transiting through a T1.

I'd need a better traceroute with longer timeouts to get a better picture here to see if we can get anything with better routes closer to the user, but we can blame their provider for now.

**Comment by ChipWolf** [comment]
Closing as this is a carrier issue.
