### ISSUE TITLE
Grafana missing k8s metrics

### ISSUE THREAD

**Issue by ChipWolf** [ArchitectSMP/k8s-gitops#22]
prometheus-community/helm-charts#576

**Comment by ChipWolf** [comment]
Fix didn't resolve the issue.

**Comment by ChipWolf** [comment]
This is fixed upstream, we should update k3s, we could close #39 at the same time
k3s-io/k3s#2831 kubernetes/kubernetes#97006

**Comment by bloodycoffin** [comment]
Has k3s been updated or how can this be executed so we can close these 2 issues?
@ChipWolf

**Comment by ChipWolf** [comment]
I feel we should do this, #21, #39, and what we have discussed in #41 at the same time.

**Comment by bloodycoffin** [comment]
@ChipWolf you wanted to look at #41 due to how long the backup was taking on Dev, let me know when you make progress on that so we can move forward with these

**Comment by ChipWolf** [comment]
Resolved following update to k3s.
