### ISSUE TITLE
If you wish to use IP forwarding, please enable it in your BungeeCord config as well!

### ISSUE THREAD

**Issue by bloodycoffin** [ArchitectSMP/k8s-gitops#25]
Players have to re-enter the game several times to circumvent this error that prevents them from entering.

The problem is not for specific regions, all players seem affected at random intervals.

**Comment by ChipWolf** [comment]
I believe this may be fixed by swapping the LoadBalancer IP on the proxy service with one from the pool rather than the primary address

**Comment by ChipWolf** [comment]
Fixed by #54
