### ISSUE TITLE
IllegalStateException - Connection Lost error

### ISSUE THREAD

**Issue by bloodycoffin** [ArchitectSMP/k8s-gitops#26]
IllegalStateException : Adding 1 elements would exceed capacity of 128 @ com.google.common.base.Preconditions:593

Received by player _RoAd_, no other players were kicked at this moment in time or have reported this error

**Comment by ChipWolf** [comment]
I found some references to this online in relation to Waterfall, it sounds like it's something which is fixed downstream.

**Comment by ChipWolf** [comment]
Unable to replicate, no instructions to replicate. Invalid & closed.
