### ISSUE TITLE
Players disconnected on join latest ProtocolLib Dev Build 526

### ISSUE THREAD

**Issue by bloodycoffin** [ArchitectSMP/k8s-gitops#308]
dmulloy2/ProtocolLib#1287

Same problem as referenced issue on ProtocolLib with the error message and all, however there are no additional plugins listed in this issue

@dmulloy2 
Did some testing considering we use PremiumVanish which has a dependency on ProtocolLib and found out that people with the PremiumVanish permissions are kicked out while people without the permissions can play just fine. We use LuckPerms for assigning the permissions.
Considering PremiumVanish works fine with ProtocolLib 4.6.1 but 1.17 version does not work with the latest dev build 526 something is wrong there. Hope this helps in finding out the problem! :-)

**Comment by ImHumbug** [comment]
I use PremiumVanish too but users without perms is not a factor for the error

**Comment by bloodycoffin** [comment]
@LeonMangler FYI

**Comment by bloodycoffin** [comment]
Problem fixed after removing Config file

**Comment by LeonMangler** [comment]
The issue with players not being able to join when another player is vanished on 1.17 servers should be fixed in the latest PV release.
