### ISSUE TITLE
Mob cap easily reached

### ISSUE THREAD

**Issue by bloodycoffin** [ArchitectSMP/k8s-gitops#33]
There are situations where the mob cap is easily reached due to the minority of players saturating the majority of the mob limit. Mob farms and unlit caves are the primary reasons.

**Comment by ChipWolf** [comment]
The [**per-player-mob-spawns**](https://paper.readthedocs.io/en/latest/server/configuration.html#per-player-mob-spawns) config option might be the first step in resolving this issue, it was implemented in PaperMC/Paper#2171. This used to exist as [a plugin](https://www.spigotmc.org/resources/distributedmobspawns.67599), it was then added to Paper directly.

Unfortunately, I don't believe it's the entire solution. This [Reddit thread](https://www.reddit.com/r/admincraft/comments/entadj/do_you_recommend_perplayermobspawns_or_not/fe5hnbj/) involving a PaperMC developer, @boyetronic, highlights some of the considerations around the use of **per-player-mob-spawns**:
> **per-player-mobs-spawns** doesn't change how the limit is calculated
> The limit is calculated globally based on the number of players, basically, `mob limit * player count / 289`
> Enabling this option might artificially seem to increase the mob limit
> The idea is that instead of a bunch of players amassing a hefty % of the limit and other players getting a smaller count and obviously being upset about that, you can instead apply the limit per player, and reduce the mob limit overall and have a more consistent experience
> It's a case of toying with the values and seeing what works for you - mob spawning, in general, is a mess
> I've seen people pull the mob limit down to mid-30s and still complain of having too many mobs
> I'd say 45 is a good starting point and tweak as needed

Additionally; I found an [interesting write-up](https://papermc.io/forums/t/changes-to-the-mob-cap-in-latest-paper-builds/672) on the mob spawn changes in Paper from 1.13+ which highlights some other issues.
