### ISSUE TITLE
Renovate should automatically merge minor/patch updates for non-user-facing services

### ISSUE THREAD

**Issue by ChipWolf** [ArchitectSMP/k8s-gitops#34]
Renovate generates many pull requests for minor changes, changes which do not impact end-users should be automatically merged to prevent process apathy.
Equally, we should look at configuring Renovate to only run during certain maintenance windows so changes can be bundled to further reduce noise. Also, the dependency dashboard can likely be closed when no pull requests are pending.

**Comment by ChipWolf** [comment]
RfC @bloodycoffin

**Comment by bloodycoffin** [comment]
How would we go about implementing this? @ChipWolf

**Comment by ChipWolf** [comment]
By setting [autoMerge](https://docs.renovatebot.com/configuration-options/#automerge), [schedule](https://docs.renovatebot.com/configuration-options/#schedule), [dependencyDashboardAutoclose](https://docs.renovatebot.com/configuration-options/#dependencydashboardautoclose), and potentially [stabilityDays](https://docs.renovatebot.com/configuration-options/#stabilitydays) in our [renovate.json5](https://github.com/ArchitectSMP/k8s-gitops/blob/main/.github/renovate.json5).
I mainly requested your comments for the scheduling

**Comment by bloodycoffin** [comment]
I believe these pull requests ought to be scheduled once a day to automatically process?
