### ISSUE TITLE
Better storage mechanism for volumes & backups

### ISSUE THREAD

**Issue by ChipWolf** [ArchitectSMP/k8s-gitops#41]
Currently, we use the [`local-path` provisioner](https://github.com/rancher/local-path-provisioner) which utilizes the local storage on the node for our persistent volumes.

This is not ideal for a few reasons:

- The node effectively becomes a pet as there's no redundancy & we depend on 100% uptime.
- Restoring the data in the event of a node outage would be a manual process with noticeable downtime.
- There's no hot failover functionality or ability to scale/move pods between nodes.
- Pods that require a persistent volume depend on remaining in the same node the `local-path` volume was created.

~~A solution would be to use [Rook](https://rook.io/); this creates a virtual storage layer where volumes can exist.~~ This will also open up the floor to [Velero](https://velero.io/) as a reliable backup & restore mechanism. It would also permit nodes to be removed/recycled & additional nodes to be seamlessly introduced to the cluster without downtime or affecting users.

**Update:** I decided against Rook for a few different reasons, mainly that it doesn't support `hostpath` & because I wanted to use OpenEBS 😅

**Comment by ChipWolf** [comment]
OpenEBS is now running & tested. The remaining volumes are the Minecraft stack, this will require a little bit of downtime to migrate the volume data to the new location. @bloodycoffin wen hop?

**Comment by bloodycoffin** [comment]
@ChipWolf let me know when is okay for you and I will make the announcement in-game.
