### ISSUE TITLE
Players do not display as AFK on the tablist when using the /afk command

### ISSUE THREAD

**Issue by bloodycoffin** [ArchitectSMP/k8s-gitops#47]
Players do not display as AFK on the tablist when using the /afk command

TAB does support AFK plugins, we just need to find out which one.

**Comment by ChipWolf** [comment]
I've engaged with @neznamy on the TAB Discord, will have a solve soon

**Comment by ChipWolf** [comment]
![](https://i.cwlf.uk/ndK68)
https://github.com/NEZNAMY/TAB/wiki/How-to-set-up-PlaceholderAPI-support-on-bungeecord
https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Placeholder-output-replacements-(premium-only)

**Comment by ChipWolf** [comment]
@bloodycoffin RfC, mainly in regards to premium replacements.

**Comment by ChipWolf** [comment]
Resolved with `xAntiAFK` in dev.
