### ISSUE TITLE
Players have two join messages, one for network, one for server

### ISSUE THREAD

**Issue by bloodycoffin** [ArchitectSMP/k8s-gitops#48]
Players have two join messages, one for network, one for server.
We need to remove the network join/leave message somehow.

**Comment by ChipWolf** [comment]
I believe this is solved, the wrong worlds were listed in the HideStream config on survival, please verify

**Comment by ChipWolf** [comment]
https://github.com/ArchitectSMP/k8s-gitops/issues/48#issuecomment-778694760 has been verified
