### ISSUE TITLE
Proxy Service for improving American connection to server

### ISSUE THREAD

**Issue by bloodycoffin** [ArchitectSMP/k8s-gitops#52]
Look into Proxy Service for improving American connection to server

**Comment by ChipWolf** [comment]
This is blocked by #22, as many of the available services are billed by bandwidth & we don't have good visibility of that yet.

**Comment by bloodycoffin** [comment]
@ChipWolf #22 is now closed, so we can examine how much bandwidth we do use for any available services and their costs

**Comment by ChipWolf** [comment]
Looks like our American friends are not having any significant issues in general, so I'm closing this for now.
